patch:
  switches/@next:
    name: emoji_suggestion
    reset: 0
    states: [ "🈚️", "🈶️" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
  menu/page_size: 6
  engine/filters/+:
  - lua_filter@Multiline_filter
  engine/translators/+:
  - table_translator@custom_phrase
  - lua_translator@date_translator
  - lua_translator@daxie_translator
  - lua_translator@UnicodeTranslator
  - lua_translator@Emoji_Translator
  - lua_translator@tips

  punctuator/import_preset: symbols
  #recognizer/patterns/punct: '^/(([a-z]+)|(uc[0-9a-fA-F]{0,6}([^0-9a-fA-F]+[0-9a-fA-F]{0,6})*|\d{0,8}[hq]?(\d+)?[^0-9]?|1?\d|dx\d+(\.\d{0,2})?|\d+[hq]|[1-7][sxz]))$'
  recognizer/patterns/punct: '^/(([a-z]+)|\?|(uc[0-9a-fA-F]{0,6}([^0-9a-fA-F]+[0-9a-fA-F]{0,6})*|\d{0,8}([hq]\d+)?[^0-9]?|\d{0,8}g|1?\d|dx\d+(\.\d{0,2})?|\d{1,6}[hq]|[1-7][sxz]))$'

  key_binder/bindings:
    - { accept: semicolon, send: 2, when: has_menu}  #打字时，冒号选中第2个候选字发送
    - { accept: apostrophe, send: 3, when: has_menu} #打字时，引号选中第3个候选字发送
    - { accept: minus, send: Page_Up, when: paging} #减号向前翻页
    - { accept: equal, send: Page_Down, when: has_menu} #等于号向后翻页
